#descomentar para correr en minikube , vor a los pv de minikubes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv
  accessModes:
    - ReadWriteMany
  #    - ReadWriteOnce
  storageClassName: ""
  #  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
